### ISSUE TITLE
does this support swift, or obj-c only?

### ISSUE THREAD

**Issue by cmnewfan** [HJaycee/JCAlertController#1]
if not, then do you have a plan to support swift?

**Comment by HJaycee** [comment]
If I use swift later, I will support it.

**Comment by mrr1vfe** [comment]
其实可以在Swift里用的 弄一个Bridger就ok了 语法变成了这个样子
JCAlertView.showOneButton(withTitle: "This is the end of all picture", message: "You cannot swipe more", buttonType: JCAlertViewButtonType.default, buttonTitle: "OK", click: nil)
