### ISSUE TITLE
自定义View问题 

### ISSUE THREAD

**Issue by Lyansun** [HJaycee/JCAlertController#13]
我自定义一个View，在JCAlert初始化时使用custom加载
现在的问题是：我在UIView有取消按钮，这样我要怎么调用JC的dismiss？

**Comment by HJaycee** [comment]
1.引用alert对象
2.取消按钮调用这个方法
- (void)dismissAlert {
    [self.alert dismissWithCompletion:^{
    }];
}

**Comment by hehedalulu** [comment]
我使用了 
```
- (void)dismissAlert { [self.alert dismissWithCompletion:^{ }]; }
```
这个方法可是并没有dismiss。。。

**Comment by HJaycee** [comment]
不会啊 demo里我就是这样调用的
