### ISSUE TITLE
为什么又把 [jCSingleTon shareSingleTon].backgroundWindow = nil 去掉了 ?

### ISSUE THREAD

**Issue by TWH-KKK** [HJaycee/JCAlertController#16]
去掉后又出现不释放的bug了

**Comment by HJaycee** [comment]
是的，原来的alertVIew代码逻辑有点乱，这段时间我用UIViewController重新写了一套，可以看下哦

**Comment by wobangnidashui** [comment]
使用UIViewController写的风格不搭啊，又要改源代码？

老版的JCAlertView弹框会影响到其它加在keywindow的展示页面，我查了半天在toggleKeyWindow加了这句[jCSingleTon shareSingleTon].backgroundWindow = nil；就好了。突然又发现了这个问题，那你究竟是为什么又去掉呢？

**Comment by wobangnidashui** [comment]
新版的风格不搭啊，又要改源代码？

老版的JCAlertView弹框会影响到其它加在keywindow的展示页面，我查了半天在toggleKeyWindow加了这句[jCSingleTon shareSingleTon].backgroundWindow = nil；就好了。突然又发现了这个问题，那你究竟是为什么又去掉呢？

**Comment by HJaycee** [comment]
其它人提pull request帮忙我修复了一些BUG，我没注意到这里又被改回去了。。如果你还是想用老的版本的话，仓库地址在`https://github.com/HJaycee/JCAlertView`，也可以用pods导入，不过不能和现在这个版本一起导入，`JCAlertView`这个类会报重复冲突
