### ISSUE TITLE
新的JCAlertController按钮风格变了

### ISSUE THREAD

**Issue by linjiaxing1992** [HJaycee/JCAlertController#18]
有没有办法呈现出以前按钮的风格？就是按钮是矩形方块的那种😝

**Comment by HJaycee** [comment]
不能哦

**Comment by linjiaxing1992** [comment]
那用之前的JCAlertview与现在的JCAlertController相比，有什么缺陷吗？

**Comment by HJaycee** [comment]
&emsp;JCAlertview是加在window上的view，偶尔会和其它window冲突，比如状态栏颜色突然变了，还有它不支持转屏，而且有一些小bug。<br>&emsp;苹果现在推荐用UIAlertController，所以继承自UIViewController来实现弹窗效果更正统一些。如果你想继续用JCAlertview也是可以的，支持cocoapods，仓库地址在https://github.com/HJaycee/JCAlertView<br>
