### ISSUE TITLE
pod不了。。pod search找不到哦

### ISSUE THREAD

**Issue by jianmu297** [HJaycee/JCAlertController#19]
如题

**Comment by HJaycee** [comment]
没问题的，你看下是不是拼写错了

**Comment by Rx3301** [comment]
真的找不到欸

**Comment by HJaycee** [comment]
这是cocoapods的bug，新的库搜不到的解决办法：
1.pod repo update // 更新pods本地仓库
2.rm ~/Library/Caches/CocoaPods/search_index.json // 删除搜索索引文件
3.pod search JCAlertController // 搜索库，能搜到就可以导入库到项目中了
