### ISSUE TITLE
FIFO和LIFO自动管理modal控制器

### ISSUE THREAD

**Issue by sunzhongliangde** [HJaycee/JCAlertController#21]
增加弹窗的优先级，
在LIFO的基础上才能实现多次弹框的重要性，优先级高的先显示出来.

**Comment by HJaycee** [comment]
目前是和UIAlertView的效果一样的，如果需要定制弹窗优先级，可以fork一份代码改下UIViewController+JCPresentQueue.h这个分类

**Comment by sunzhongliangde** [comment]
还有一个需求就是，点击背景层的时候能不能加一个属性来控制是否允许关闭弹窗，因为系统的弹窗是点击背景层不消失弹窗

**Comment by HJaycee** [comment]
@interface JCAlertStyleBackground : NSObject
@property (nonatomic) BOOL blur;
@property (nonatomic) BOOL canDismiss; // dismissed with touched the bg
@property (nonatomic) float alpha;
@end

把canDismiss设置NO就可以
