### ISSUE TITLE
不支持转屏？

### ISSUE THREAD

**Issue by TheLittleBoy** [HJaycee/JCAlertController#6]
如果能支持转屏就更好了。

**Comment by HJaycee** [comment]
是的，不支持~

**Comment by demoker** [comment]
最近在弄这个转屏，不知作者有什么好的建议吗？

**Comment by HJaycee** [comment]
布局是用算坐标来写的，转屏要重新写一套frame，应该会挺麻烦的吧

**Comment by demoker** [comment]
目前，我这边根据约束写了一部分，但是横竖屏切换的时候，还是会有问题，不知道怎么去处理了,[点击查看demo](https://github.com/demoker/MDAlertView.git)

**Comment by HJaycee** [comment]
你的仓库没有代码啊？我没有支持转屏因为文字多了以后alert高度会很高，转屏的时候要重新给个最高高度

**Comment by demoker** [comment]
Hi，你重新看下，刚没推送

**Comment by HJaycee** [comment]
我试了在TwoViewController的viewDidLoad里，在alert弹出前加了一秒延时，alert就可以横过来了，你再多调试下吧
