### ISSUE TITLE
弹出之后，顶部状态栏的问题

### ISSUE THREAD

**Issue by CoderDiLi** [HJaycee/JCAlertController#8]
UINavigationBar *navBar = [UINavigationBar appearance];
[navBar setBarStyle:UIBarStyleBlack];

顶部状态栏文字原本设成白色的，点开JCAlertView之后，变成黑色了，半天没找到在哪里设置的

**Comment by HJaycee** [comment]
[UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleLightContent;
用UIApplication单例来设置状态栏的话alert弹出不会改变颜色的

**Comment by LimyronChin** [comment]
Maybe there is a way to resolve this problem. We can change the level of UIWindow which is used to contain JCAlertViewController to UIWindowLevelAlert, then when AlertView is show, the JCAlertView is not the top window, it will change the statusBar, but when the AlertView is dismissed and we changed to other UIViewController the StatusBar will be Normal.
