### ISSUE TITLE
如果有一些页面想写在JCAlertView前面，需要怎样实现？

### ISSUE THREAD

**Issue by SaraZheng** [HJaycee/JCAlertController#9]
初入门的新手有个疑问求解答。
我借用了JCAlertView写了一个PopView，其中用了UIImagePickerController想要获取相册图片，但是弹出来的这个Picker却一直都在JCAlertView下面，只有dismiss了JCAlertView才能显示出Picker。
想请教一下这个问题有什么办法解决？如果还有一些页面想写在JCAlertView前面，需要怎样实现？

**Comment by HJaycee** [comment]
内部实现是创建了一个新的window，这个window的优先级低于状态栏。要让页面盖在alert上面的话，也要用window，而且优先级高于状态栏才可以

**Comment by SilverZheng** [comment]
谢谢！学习了~完美解决！
